name: charity_app
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  pin_code_fields: ^8.0.1
  intl: ^0.18.0
  connectivity_plus: ^5.0.2
  bloc: ^8.1.4
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.1
  equatable: ^2.0.5
  flutter_screenutil: 5.9.0
  flutter_svg: ^2.0.10+1
  google_fonts: 6.1.0
  go_router: ^14.0.2
  injectable: ^2.3.5
  get_it: ^7.2.0

dev_dependencies: 
  flutter_test: 
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.3.2
  injectable_generator: ^2.4.2
  build_runner: ^2.3.3

flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/images/nav/
  fonts:
    - family: Josefin Sans
      fonts: 
        - asset: assets/fonts/JosefinSansRomanBold.ttf
          weight: 700
        - asset: assets/fonts/JosefinSansRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/JosefinSansRomanSemiBold.ttf
          weight: 600
    - family: Jost
      fonts: 
        - asset: assets/fonts/JostRomanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/JostRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/JostRomanMedium.ttf
          weight: 500
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRomanBold.ttf
          weight: 700
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/RobotoMedium.ttf
          weight: 500
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoRomanLight.ttf
          weight: 300
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
